global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "csharp-app"
    static_configs:
      - targets: ["custom-metrics-aspnetapp:8080"]
    metrics_path: /metrics
